name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOSTIP }}
          username: ${{ secrets.EC2_USERID }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            echo "Navigating to project directory..."
            cd ~/DockerProject

            echo "Updating latest code..."
            git reset --hard
            git pull origin main

            echo "Building Docker image..."
            sudo docker build -t myapp:latest .

            echo "Stopping old container (if exists)..."
            sudo docker stop myapp || true

            echo "Removing old container (if exists)..."
            sudo docker rm myapp || true

            echo "Starting new container..."
            sudo docker run -d --name myapp -p 80:80 myapp:latest
